### ISSUE TITLE
无法加载 Yaf\Application 的错误

### ISSUE THREAD

**Issue by garylab** [loncool/yaf-admin#2]
Yaf似乎不支持命名空间，配置完访问出错：
Fatal error: Class 'Yaf\Application' not found in E:\www\shop.com\public\index.php on line 21
是什么原因

**Comment by zhoushenn** [comment]
yaf默认没有开启命名空间支持， 你需要修改php.ini文件，加入yaf.use_namespace=1;

**Comment by garylab** [comment]
加了，这个错误有没了。但是又提示：
`
Warning: require(E:\www\shop.com/vendor/autoload.php): failed to open stream: No such file or directory in E:\www\shop.com\public\index.php on line 23

Fatal error: require(): Failed opening required 'E:\www\shop.com/vendor/autoload.php' (include_path='.;C:\php\pear') in E:\www\shop.com\public\index.php on line 23`
这个是什么原因呢？

**Comment by zhoushenn** [comment]
你需要在根目录下运行composer install 来安装依赖库。

**Comment by garylab** [comment]
好的，我试试，这些要是能写到README里面就好了

**Comment by garylab** [comment]
运行 composer install 安装了依赖库，还挺大的，40M，现在medoo错误，

`Fatal error: Call to a member function errorInfo() on null in E:\www\shop.com\core\Medoo.php on line 948`

难道是数据库配置错误，检查了即便似乎没错呀，环境Apache+PHP5.6n

**Comment by liuqi666** [comment]
怎么安装依赖库？

**Comment by ryanflys** [comment]
请问我composer也安装了依赖库，yaf命名空间也开启了，怎么还报这个错t-t
`Warning: Yaf\Loader::autoload(): Failed opening script C:\wamp\www\yaf-admin-master\yaf-admin-master/library\PhpParser\Autoloader.php: No such file or directory in C:\wamp\www\yaf-admin-master\yaf-admin-master\vendor\nikic\php-parser\lib\bootstrap.php on line 3`

`Fatal error: Call to a member function errorInfo() on null in C:\wamp\www\yaf-admin-master\yaf-admin-master\core\Medoo.php on line 948`

**Comment by mrzeta** [comment]
将vendor 里面的nikic文件夹下的PhpParser 贴到你对应的library里面就好了~~ 然后你在访问会是一片空白- -！

**Comment by jenqz** [comment]
开发环境默认是product,.ini文件里只配置了dev的，所以数据库配置没找到。

**Comment by lastying** [comment]
请问composer安装了依赖库，为什么还报这个错误
Warning: Yaf\Loader::autoload(): Failed opening script D:\phpWeb\Yaf\yaf-admin-master/library\PhpParser\Autoloader.php: No such file or directory in D:\phpWeb\Yaf\yaf-admin-master\vendor\nikic\php-parser\lib\bootstrap.php on line 3

Warning: Yaf\Loader::autoload(): Failed opening script D:\phpWeb\Yaf\yaf-admin-master/library\Core\ServiceLocator.php: No such file or directory in D:\phpWeb\Yaf\yaf-admin-master\application\Bootstrap.php on line 24

Fatal error: Uncaught Error: Class 'Core\ServiceLocator' not found in D:\phpWeb\Yaf\yaf-admin-master\application\Bootstrap.php:24 Stack trace: #0 [internal function]: Bootstrap->_initService(Object(Yaf\Dispatcher)) #1 D:\phpWeb\Yaf\yaf-admin-master\public\index.php(24): Yaf\Application->bootstrap() #2 {main} thrown in D:\phpWeb\Yaf\yaf-admin-master\application\Bootstrap.php on line 24
